Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/stable-baselines3/main_lowvar.py", line 4, in <module>
  File "/home/zhang146/stable-baselines3/main_lowvar.py", line 4, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 25, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 25, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 19, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 19, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/__init__.py", line 485, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/__init__.py", line 485, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/distributions.py", line 8, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/distributions.py", line 8, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 22, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/__init__.py", line 200, in __getattr__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/__init__.py", line 200, in __getattr__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 405, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 406, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 25, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_root.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_lsq/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_lsq/lsq_linear.py", line 9, in <module>
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_trustregion_exact.py'
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_lsq/trf_linear.py'
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/stable-baselines3/main_lowvar.py", line 4, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 25, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 19, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/__init__.py", line 485, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/distributions.py", line 8, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/__init__.py", line 200, in __getattr__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 406, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_root.py", line 19, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py", line 14, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_lsq/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/stable-baselines3/main_lowvar.py", line 4, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/__init__.py", line 82, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/base.py", line 17, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 25, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/sklearn/utils/fixes.py", line 19, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/__init__.py", line 485, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/distributions.py", line 8, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/__init__.py", line 200, in __getattr__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/importlib/__init__.py", line 126, in import_module
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 405, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_trustregion_exact.py'
  File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/scipy/optimize/_lsq'
Traceback (most recent call last):
  File "/home/zhang146/stable-baselines3/main_lowvar.py", line 943, in <module>
    dummy_env = SubprocVecEnv(dummy_env_fns)
  File "/home/zhang146/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 119, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
